const PagoRegistrar = require('./pago.registrar'); 
const PagoBuscar = require('./pago.buscar'); 
const PagoEliminar = require('./pago.eliminar'); 
const PagoActualizar = require('./pago.actualizar');
const PagoMongo = require('../infraestructura/pago.mongo');
const pagoCreate = PagoRegistrar(PagoMongo); 
const pagoSearch = PagoBuscar(PagoMongo); 
const pagoEliminate = PagoEliminar(PagoMongo); 
const pagoUpdate = PagoActualizar(PagoMongo);
module.exports = { pagoCreate, pagoSearch, pagoEliminate, pagoUpdate } 