const UsuarioRegistrar = require('./usuario.registrar');
const UsuarioBuscar = require('./usuario.buscar');
const UsuarioEliminar = require('./usuario.eliminar');
const UsuarioActualizar = require('./usuario.actualizar');
const UsuarioLogin = require("../aplicacion/usuario.login");
const UsuarioMongo = require('../infraestructura/usuario.mongo');
const usuarioCreate = UsuarioRegistrar(UsuarioMongo);
const usuarioSearch = UsuarioBuscar(UsuarioMongo);
const usuarioEliminate = UsuarioEliminar(UsuarioMongo);
const usuarioUpdate = UsuarioActualizar(UsuarioMongo);
const usuarioLogon = UsuarioLogin(UsuarioMongo);
module.exports = { usuarioCreate, usuarioSearch, usuarioEliminate, usuarioUpdate, usuarioLogon }